version: '3.7'

services:

  repository-search-elastic:
    image: "${docker.repository}/edu_sharing-community-repository-plugin-elastic-deploy-docker-build-elasticsearch:${docker.tag}"
    environment:
      ES_JAVA_OPTS: >-
        -Xms${REPOSITORY_SEARCH_ELASTIC_JAVA_XMS:-1g}
        -Xmx${REPOSITORY_SEARCH_ELASTIC_JAVA_XMX:-1g}
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.port=7199
        -Dcom.sun.management.jmxremote.ssl=false
      discovery.type: "single-node"
      cluster.routing.allocation.disk.threshold_enabled: "false"
    expose:
      - "7199"
      - "9200"
      - "9300"
    volumes:
      - "repository-search-elastic-volume:/usr/share/elasticsearch/data"

  repository-search-elastic-tracker:
    image: "${docker.repository}/edu_sharing-community-repository-plugin-elastic-deploy-docker-build-tracker:${docker.tag}"
    command:
      - -Xms${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMS:-1g}
      - -Xmx${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMX:-1g}
      - -Dcom.sun.management.jmxremote
      - -Dcom.sun.management.jmxremote.authenticate=false
      - -Dcom.sun.management.jmxremote.port=7199
      - -Dcom.sun.management.jmxremote.ssl=false
    environment:
      REPOSITORY_SEARCH_ELASTIC_HOST: repository-search-elastic
      REPOSITORY_SEARCH_ELASTIC_PORT: "9200"
      REPOSITORY_SERVICE_HOST: repository-service
      REPOSITORY_SERVICE_PORT: "8080"
      REPOSITORY_SERVICE_ADMIN_PASS: "${REPOSITORY_SERVICE_ADMIN_PASS:-admin}"
    expose:
      - "7199"
    depends_on:
      - repository-search-elastic
      - repository-service

  repository-service:
    environment:
      REPOSITORY_SEARCH_ELASTIC_HOST: repository-search-elastic
      REPOSITORY_SEARCH_ELASTIC_PORT: "9200"
    depends_on:
      - repository-search-elastic

volumes:
  repository-search-elastic-volume: