repos:
  - repo: https://github.com/bitnami/readme-generator-for-helm
    rev: "2.6.1"
    hooks:
    - id: helm-readme-generator-index
      pass_filenames: false
      always_run: true
      args: [--readme=deploy/docker/helm/index/src/main/chart/README.md, --values=deploy/docker/helm/index/src/main/chart/values.yaml]
    - id: helm-readme-generator-tracker
      pass_filenames: false
      always_run: true
      args: [--readme=deploy/docker/helm/tracker/src/main/chart/README.md, --values=deploy/docker/helm/tracker/src/main/chart/values.yaml]
