version: "3.7"
services:

  tracker:
    build: . 
    environment: 
      - |
        "JAVA_TOOL_OPTIONS=
        logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %logger{36}.%M - %msg%n
        server.port=8081
        alfresco.host=localhost
        alfresco.port=8080
        alfresco.protocol=http
        alfresco.username=admin
        alfresco.password=admin
        elastic.host=localhost
        elastic.port=9200
        elastic.protocol=http
        elastic.socketTimeout=-1
        elastic.connectTimeout=-1
        elastic.connectionRequestTimeout=-1
        allowed.types=ccm:io,ccm:map,ccm:usage
        valuespace.languages=de_DE,en_US
        valuespace.cache.check.after.ms=120000
        index.storerefs=workspace://SpacesStore,archive://SpacesStore
        tracker.fetchThumbnails = true
        threading.threadCount = 4"
 
