version: "3.7"
services:

  elastic:
    image: "elasticsearch:8.3.2"
    environment:
      ES_JAVA_OPTS: >-
        -Xms${REPOSITORY_SEARCH_ELASTIC_INDEX_JAVA_XMS:-512m}
        -Xmx${REPOSITORY_SEARCH_ELASTIC_INDEX_JAVA_XMX:-512m}
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.port=7199
        -Dcom.sun.management.jmxremote.ssl=false
      discovery.type: "single-node"
      cluster.routing.allocation.disk.threshold_enabled: "false"
    ports:
      - "7199:7199"
      - "9200:9200"
      - "9300:9300"

  tracker:
    build: . 
    environment: 
      - |
        "JAVA_TOOL_OPTIONS=
        logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %logger{36}.%M - %msg%n
        server.port=8081
        alfresco.host=localhost
        alfresco.port=8080
        alfresco.protocol=http
        alfresco.username=admin
        alfresco.password=admin
        elastic.host=localhost
        elastic.port=9200
        elastic.protocol=http
        elastic.socketTimeout=-1
        elastic.connectTimeout=-1
        elastic.connectionRequestTimeout=-1
        valuespace.languages=de_DE,en_US
        valuespace.cache.check.after.ms=120000
        index.storerefs=workspace://SpacesStore,archive://SpacesStore
        tracker.fetchThumbnails = true
        threading.threadCount = 4"
 
