apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-env
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
data:
  JAVA_OPTS: >-
    {{- with .Values.config.jvm.ram.minPercentage }}
    -XX:InitialRAMPercentage={{ . }}
    {{- end }}
    {{- with .Values.config.jvm.ram.maxPercentage }}
    -XX:MaxRAMPercentage={{ . }}
    {{- end }}    
    -Dcom.sun.management.jmxremote
    -Dcom.sun.management.jmxremote.authenticate=false
    -Dcom.sun.management.jmxremote.port=7199
    -Dcom.sun.management.jmxremote.ssl=false
    {{- if default .Values.global.debug .Values.debug }}
    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005
    {{- end }}
  REPOSITORY_SEARCH_ELASTIC_INDEX_HOST: {{ .Values.config.search.elastic.host | quote }}
  REPOSITORY_SEARCH_ELASTIC_INDEX_PORT: {{ .Values.config.search.elastic.port | quote }}
  REPOSITORY_SEARCH_ELASTIC_INDEX_REPLICAS: {{ .Values.config.search.elastic.index.replicas | quote }}
  REPOSITORY_SEARCH_ELASTIC_INDEX_SHARDS: {{ .Values.config.search.elastic.index.shards | quote }}
  REPOSITORY_SEARCH_ELASTIC_TRACKER_MANAGEMENT_BIND: "0.0.0.0"
  REPOSITORY_SERVICE_HOST: {{ .Values.config.repository.host | quote }}
  REPOSITORY_SERVICE_PORT: {{ .Values.config.repository.port | quote }}
  SPRING_APPLICATION_JSON: {{ .Values.config.override | quote }}
