{{- if .Values.job.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-migration
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
    app.kubernetes.io/component: migration
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        {{- with merge .Values.job.migration.podAnnotations .Values.global.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ include "edusharing_common_lib.names.name" . }}
        image: {{ include "edusharing_common_lib.images.image" . }}{{ .Values.job.migration.image.name }}:{{ .Values.job.migration.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        args:
          - --mode=migration-only
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_common_lib.names.name" . }}-env
        - secretRef:
            name: {{ include "edusharing_common_lib.names.name" . }}-env
        {{- if .Values.config.tracker.customScript }}
        volumeMounts:
          - name: script
            mountPath: /opt/alfresco/scripts/script.groovy
            subPath: script.groovy
            readOnly: true
        {{- end }}
        ports:
        - name: management
          containerPort: 8081
        {{- if default .Values.global.debug .Values.debug }}
        - name: jpda
          containerPort: 5005
        {{- end }}
        {{- with .Values.job.migration.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.job.migration.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.config.tracker.customScript }}
      volumes:
        - configMap:
            name: {{ include "edusharing_common_lib.names.name" . }}-script
          name: script
      {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with merge .Values.podSecurityContext .Values.global.security }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.nodeAffinity }}
      affinity:
        nodeAffinity: {{ toYaml . | nindent 10 }}
      {{- end }}
{{- end }}