apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-env
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
type: Opaque
data:
  REPOSITORY_SERVICE_ADMIN_PASS: {{ default .Values.global.password .Values.config.repository.password | b64enc | quote }}