{{- if and .Values.global.metrics.servicemonitor.enabled .Values.config.metrics }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "edusharing_repository_search_elastic_tracker.name" . }}
  labels: {{ include "edusharing_repository_search_elastic_tracker.labels.app" . | nindent 4 }}
    app.kubernetes.io/component: "metrics"
spec:
  endpoints:
  - path: "/actuator/prometheus"
    port: http-management
  selector:
    matchLabels: {{ include "edusharing_repository_search_elastic_tracker.labels.app" . | nindent 6 }}
      app.kubernetes.io/component: "metrics"
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
{{- end }}
