apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "edusharing_repository_search_elastic_tracker.name" . }}
  labels: {{ include "edusharing_repository_search_elastic_tracker.labels.app" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "edusharing_repository_search_elastic_tracker.labels.app" . | nindent 6 }}
  serviceName: {{ include "edusharing_repository_search_elastic_tracker.name" . }}-headless
  template:
    metadata:
      labels: {{ include "edusharing_repository_search_elastic_tracker.labels.app" . | nindent 8 }}
      annotations:
        checksum/configmap-env: {{ include (print .Template.BasePath "/configmap-env.yaml") . | sha256sum | trunc 63 }}
        checksum/secret-env: {{ include (print .Template.BasePath "/secret-env.yaml") . | sha256sum | trunc 63 }}
        {{- if not .Values.global.metrics.servicemonitor.enabled }}
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
        prometheus.io/scrape: {{ .Values.config.metrics | quote }}
        {{- end }}
        sidecar.istio.io/inject: {{ .Values.global.cluster.istio.enabled | quote }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ include "edusharing_repository_search_elastic_tracker.name" . }}
        image: {{ include "edusharing_repository_search_elastic_tracker.image" . }}{{ .Values.image.prefix }}-deploy-docker-build-tracker:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_repository_search_elastic_tracker.name" . }}-env
        - secretRef:
            name: {{ include "edusharing_repository_search_elastic_tracker.name" . }}-env
        ports:
        - name: management
          containerPort: 8081
        {{- if .Values.debug }}
        - name: jpda
          containerPort: 5005
        {{- end }}
        {{- with .Values.startupProbe }}
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: management
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: management
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: management
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.nodeAffinity }}
      affinity:
        nodeAffinity: {{ toYaml . | nindent 10 }}
      {{- end }}
