apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_repository_search_elastic_index.name" . }}-env
  labels: {{ include "edusharing_repository_search_elastic_index.labels.app" . | nindent 4 }}
data:
  ES_JAVA_OPTS: >-
    {{- with .Values.config.jvm.ram.minPercentage }}
    -XX:InitialRAMPercentage={{ . }}
    {{- end }}
    {{- with .Values.config.jvm.ram.maxPercentage }}
    -XX:MaxRAMPercentage={{ . }}
    {{- end }}    
    -Dcom.sun.management.jmxremote
    -Dcom.sun.management.jmxremote.authenticate=false
    -Dcom.sun.management.jmxremote.port=7199
    -Dcom.sun.management.jmxremote.ssl=false
    {{- if default .Values.global.debug .Values.debug }}
    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    {{- end }}
  node.data: "true"
  node.ingest: "true"
  node.master: "true"
  node.store.allow_mmap: "{{ .Values.config.store.mmap }}"
  xpack.security.enabled: "false"
