{{- if .Values.global.cluster.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "edusharing_repository_search_elastic_index.name" . }}
  labels: {{ include "edusharing_repository_search_elastic_index.labels.app" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels: {{ include "edusharing_repository_search_elastic_index.labels.app" . | nindent 6 }}
{{- end }}