---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
    {{- if .Values.multistage.enabled }}
    app.kubernetes.io/stage: ""
    {{- end }}
spec:
  type: ClusterIP
  selector: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
    {{- if .Values.multistage.enabled }}
    app.kubernetes.io/stage: {{ .Values.multistage.current | quote }}
    {{- end }}
  ports:
  - name: http-api
    port: {{ .Values.service.port.api }}
    targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-headless
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
    {{- if .Values.multistage.enabled }}
    app.kubernetes.io/stage: ""
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
    {{- if .Values.multistage.enabled }}
    app.kubernetes.io/stage: ""
    {{- end }}
  ports:
  - name: http-api
    port: {{ .Values.service.port.api }}
  - name: tcp-gossip
    port: {{ .Values.service.port.gossip }}
{{- if .Values.global.metrics.servicemonitor.enabled }}
{{- if .Values.sidecar.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-metrics
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
    app.kubernetes.io/component: "metrics"
    {{- if .Values.multistage.enabled }}
    app.kubernetes.io/stage: ""
    {{- end }}
spec:
  type: ClusterIP
  selector: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
    {{- if .Values.multistage.enabled }}
    app.kubernetes.io/stage: ""
    {{- end }}
  ports:
    - name: http-metrics
      port: {{ .Values.service.port.metrics }}
      targetPort: metrics
{{- end }}
{{- end }}
{{- if .Values.multistage.enabled }}
{{- range .Values.multistage.stages }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_common_lib.names.name" $ }}-{{ .name }}
  labels: {{ include "edusharing_common_lib.labels.app" $ | nindent 4 }}
    app.kubernetes.io/stage: {{ .name }}
spec:
  type: ClusterIP
  selector: {{ include "edusharing_common_lib.labels.app" $ | nindent 4 }}
    app.kubernetes.io/stage: {{ .name }}
  ports:
  - name: http-api
    port: {{ $.Values.service.port.api }}
    targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_common_lib.names.name" $ }}-headless-{{ .name }}
  labels: {{ include "edusharing_common_lib.labels.app" $ | nindent 4 }}
    app.kubernetes.io/stage: {{ .name }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector: {{ include "edusharing_common_lib.labels.app" $ | nindent 4 }}
    app.kubernetes.io/stage: {{ .name }}
  ports:
  - name: http-api
    port: {{ $.Values.service.port.api }}
  - name: tcp-gossip
    port: {{ $.Values.service.port.gossip }}
{{- if $.Values.global.metrics.servicemonitor.enabled }}
{{- if $.Values.sidecar.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_common_lib.names.name" $ }}-metrics-{{ .name }}
  labels: {{ include "edusharing_common_lib.labels.app" $ | nindent 4 }}
    app.kubernetes.io/component: "metrics"
    app.kubernetes.io/stage: {{ .name }}
spec:
  type: ClusterIP
  selector: {{ include "edusharing_common_lib.labels.app" $ | nindent 4 }}
    app.kubernetes.io/stage: {{ .name }}
  ports:
  - name: http-metrics
    port: {{ $.Values.service.port.metrics }}
    targetPort: metrics
{{- end }}
{{- end }}
{{- end }}
{{- end }}